/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.CSYE6200.daycare.UserInterface;

import edu.neu.CSYE6200.daycare.API.AbstractGroup;
import edu.neu.CSYE6200.daycare.Architecture.School;
import edu.neu.CSYE6200.daycare.Architecture.Student;
import edu.neu.CSYE6200.daycare.Architecture.Teacher;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kcnuk
 */
public class AddNewGroupJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private School school;
    private AbstractGroup group;
    private Teacher teacher;
    /**
     * Creates new form AddNewGroup
     */
    public AddNewGroupJPanel(JPanel userProcessContainer, School school) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.school = school;
        this.group = group;
        this.teacher = teacher;
        populateTeacherAssignTable();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGroupID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTeacherName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStudentNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaxNum = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeacher = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTeaAssign = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        btnStuAssign = new javax.swing.JButton();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();
        radio5 = new javax.swing.JRadioButton();
        radio6 = new javax.swing.JRadioButton();
        btnCheck = new javax.swing.JButton();

        setBackground(new java.awt.Color(216, 233, 239));

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel1.setText("Student Information:");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        jLabel3.setText("Group ID :");

        txtGroupID.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        jLabel4.setText("Teacher Name :");

        txtTeacherName.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        txtTeacherName.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        jLabel5.setText("Student Number:");

        txtStudentNum.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        txtStudentNum.setText("0");
        txtStudentNum.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        jLabel6.setText("Max Student Number:");

        txtMaxNum.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        txtMaxNum.setEnabled(false);

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(216, 233, 239));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setBackground(new java.awt.Color(0, 0, 0));
        btnCreate.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(216, 233, 239));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        tblTeacher.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        tblTeacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Teacher Name", "Group ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTeacher.setSelectionBackground(new java.awt.Color(78, 161, 211));
        jScrollPane1.setViewportView(tblTeacher);
        if (tblTeacher.getColumnModel().getColumnCount() > 0) {
            tblTeacher.getColumnModel().getColumn(0).setResizable(false);
            tblTeacher.getColumnModel().getColumn(1).setResizable(false);
            tblTeacher.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel2.setText("Assign Teacher to the Group:");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel7.setText("Assign Student to the Group:");

        jLabel8.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel8.setText("See Students in different Age: ");

        btnTeaAssign.setBackground(new java.awt.Color(0, 0, 0));
        btnTeaAssign.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnTeaAssign.setForeground(new java.awt.Color(216, 233, 239));
        btnTeaAssign.setText("Assign");
        btnTeaAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeaAssignActionPerformed(evt);
            }
        });

        tblStudent.setFont(new java.awt.Font("微软雅黑", 0, 15)); // NOI18N
        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Group ID", "Age", "First Name", "Last Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.setSelectionBackground(new java.awt.Color(78, 161, 211));
        jScrollPane2.setViewportView(tblStudent);
        if (tblStudent.getColumnModel().getColumnCount() > 0) {
            tblStudent.getColumnModel().getColumn(0).setResizable(false);
            tblStudent.getColumnModel().getColumn(1).setResizable(false);
            tblStudent.getColumnModel().getColumn(2).setResizable(false);
            tblStudent.getColumnModel().getColumn(3).setResizable(false);
            tblStudent.getColumnModel().getColumn(4).setResizable(false);
        }

        btnStuAssign.setBackground(new java.awt.Color(0, 0, 0));
        btnStuAssign.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnStuAssign.setForeground(new java.awt.Color(216, 233, 239));
        btnStuAssign.setText("Assign");
        btnStuAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStuAssignActionPerformed(evt);
            }
        });

        radio1.setBackground(new java.awt.Color(78, 161, 211));
        radio1.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        radio1.setText("6-12");
        radio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio1ActionPerformed(evt);
            }
        });

        radio2.setBackground(new java.awt.Color(78, 161, 211));
        radio2.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        radio2.setText("13-24");

        radio3.setBackground(new java.awt.Color(78, 161, 211));
        radio3.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        radio3.setText("25-35");

        radio4.setBackground(new java.awt.Color(78, 161, 211));
        radio4.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        radio4.setText("36-47");

        radio5.setBackground(new java.awt.Color(78, 161, 211));
        radio5.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        radio5.setText("48-59");

        radio6.setBackground(new java.awt.Color(78, 161, 211));
        radio6.setFont(new java.awt.Font("微软雅黑", 1, 15)); // NOI18N
        radio6.setText("60 on up");

        btnCheck.setBackground(new java.awt.Color(0, 0, 0));
        btnCheck.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(216, 233, 239));
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTeaAssign)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStudentNum, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCreate))))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(radio1)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio2)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(radio4)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio5)
                                        .addGap(18, 18, 18)
                                        .addComponent(radio6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStuAssign)
                                    .addComponent(btnCheck))))
                        .addGap(100, 100, 100))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCheck, btnStuAssign});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radio1, radio2, radio3, radio4, radio5, radio6});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTeacherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtStudentNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaxNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTeaAssign))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radio1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radio2)
                                        .addComponent(radio3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnStuAssign)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCheck))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radio4)
                                    .addComponent(radio5)
                                    .addComponent(radio6))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCheck, btnStuAssign});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {radio1, radio2, radio3, radio4, radio5, radio6});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //get the previous JPanel then pop the table again
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageGroupJPanel){
                ManageGroupJPanel panel = (ManageGroupJPanel) comp;
                panel.populateTable();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String a = txtGroupID.getText();
        try {
            Integer.parseInt(a);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID: " + a + " is not a valid int number");
            return;
        }
        int id = Integer.valueOf(a);
        
        String teacherName = txtTeacherName.getText();
        if(teacherName.equals("")){
            JOptionPane.showMessageDialog(null, "Please set a Teacher Name");
            return;
        }
        
        int studentnum = Integer.parseInt(txtStudentNum.getText());
        int maxnum = Integer.parseInt(txtMaxNum.getText());
        
        
        school.addGroup(id, teacher, studentnum, maxnum);
        

        JOptionPane.showMessageDialog(null, "Group successfully created!");         
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnStuAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStuAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStudent.getSelectedRow();
        if(selectedRow >= 0){
                Student s = (Student) tblStudent.getValueAt(selectedRow, 0);
                txtStudentNum.setText(String.valueOf(Integer.parseInt(txtStudentNum.getText())+1));
            try {
                AbstractGroup gr = school.searchGroup(Integer.parseInt(txtGroupID.getText()));
                school.addStudentToGroup(gr, s);
                populateStudentAssignTable();                
            } catch (Exception ex) {
                Logger.getLogger(AddNewGroupJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnStuAssignActionPerformed

    private void btnTeaAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeaAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTeacher.getSelectedRow();
        if(selectedRow >= 0){
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure to assign this teacher? All the related data will be changed.", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                Teacher t = (Teacher) tblTeacher.getValueAt(selectedRow, 0);
                teacher = t;
                txtTeacherName.setText(t.getFirstname());
                populateTeacherAssignTable();
                btnTeaAssign.setEnabled(false);
            }

            }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnTeaAssignActionPerformed

    private void radio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radio1ActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        populateStudentAssignTable();
    }//GEN-LAST:event_btnCheckActionPerformed

    void populateTeacherAssignTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblTeacher.getModel();
        dtm.setRowCount(0);
        for(Teacher t: school.getTeachers()){
            if(t.getGroupID() == 0){
            Object[] row = new  Object[3];
            row[0] = t;
            row[1] = t.getFirstname();
            row[2] = t.getGroupID();
            
            dtm.addRow(row);}
        }        
    }
    
    void populateStudentAssignTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblStudent.getModel();
        dtm.setRowCount(0);
        if(radio1.isSelected()){
            txtMaxNum.setText("4");
        for(Student s: school.getStudents()){
            if(s.getGroupID() == 0 && s.getAge() > 5 && s.getAge() < 13){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }          
        }else if(radio2.isSelected()){
            txtMaxNum.setText("5");
        for(Student s: school.getStudents()){
            if(s.getGroupID() == 0 && s.getAge() > 12 && s.getAge() < 25){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }            
        }else if(radio3.isSelected()){
            txtMaxNum.setText("6");
        for(Student s: school.getStudents()){
            if(s.getGroupID() == 0 && s.getAge() > 24 && s.getAge() < 36){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }            
        }else if(radio4.isSelected()){
            txtMaxNum.setText("8");
        for(Student s: school.getStudents()){
            if(s.getGroupID() == 0 && s.getAge() > 35 && s.getAge() < 48){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }            
        }else if(radio5.isSelected()){
            txtMaxNum.setText("12");
        for(Student s: school.getStudents()){
            if(s.getGroupID() == 0 && s.getAge() > 47 && s.getAge() < 60){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }            
        }else if(radio6.isSelected()){
            txtMaxNum.setText("15");
        for(Student s: school.getStudents()){
            if(s.getGroupID() == 0 && s.getAge() > 59){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }            
        }else{
        for(Student s: school.getStudents()){
            txtMaxNum.setText("0");
            if(s.getGroupID() == 0){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }              
        }
        if(Integer.parseInt(txtStudentNum.getText()) > Integer.parseInt(txtMaxNum.getText())){
            btnStuAssign.setEnabled(false);
        }
    }
    void populateTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblStudent.getModel();
        dtm.setRowCount(0);
        for(Student s: school.getStudents()){
            txtMaxNum.setText("0");
            if(s.getGroupID() == 0){
            Object[] row = new  Object[5];
            row[0] = s;
            row[1] = s.getGroupID();
            row[2] = s.getAge();
            row[3] = s.getFirstname();
            row[4] = s.getLasstname();
            
            dtm.addRow(row);}
        }              
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnStuAssign;
    private javax.swing.JButton btnTeaAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    private javax.swing.JRadioButton radio5;
    private javax.swing.JRadioButton radio6;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTable tblTeacher;
    private javax.swing.JTextField txtGroupID;
    private javax.swing.JTextField txtMaxNum;
    private javax.swing.JTextField txtStudentNum;
    private javax.swing.JTextField txtTeacherName;
    // End of variables declaration//GEN-END:variables
}
