/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.CSYE6200.daycare.UserInterface;

import edu.neu.CSYE6200.daycare.API.AbstractClassroom;
import edu.neu.CSYE6200.daycare.Architecture.Classroom;
import edu.neu.CSYE6200.daycare.Architecture.School;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kcnuk
 */
public class ManageClassroomJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private School school;

    /**
     * Creates new form ManageClassroomJPanel
     */
    public ManageClassroomJPanel(JPanel userProcessContainer, School school) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.school = school;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassRoom = new javax.swing.JTable();
        btnCheck = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(216, 233, 239));

        tblClassRoom.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        tblClassRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Classroom Name", "Group Quantitiy", "Max Group Quantity", "Students Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClassRoom);
        if (tblClassRoom.getColumnModel().getColumnCount() > 0) {
            tblClassRoom.getColumnModel().getColumn(0).setResizable(false);
            tblClassRoom.getColumnModel().getColumn(1).setResizable(false);
            tblClassRoom.getColumnModel().getColumn(2).setResizable(false);
            tblClassRoom.getColumnModel().getColumn(3).setResizable(false);
        }

        btnCheck.setBackground(new java.awt.Color(0, 0, 0));
        btnCheck.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnCheck.setForeground(new java.awt.Color(216, 233, 239));
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel1.setText("View & Update the group info of selected classroom:");

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 25)); // NOI18N
        jLabel2.setText("Classroom info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 445, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCheck))
                .addGap(80, 80, 80))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblClassRoom.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row from table first to view", "Warning", JOptionPane.WARNING_MESSAGE);
        }else{
            AbstractClassroom classroom = (AbstractClassroom)tblClassRoom.getValueAt(selectedRow, 0);
            ViewClassroomJPanel panel = new ViewClassroomJPanel(this.userProcessContainer, school, classroom);
            userProcessContainer.add("ViewClassroomJPanel", panel);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblClassRoom.getModel();
        dtm.setRowCount(0);
        for(AbstractClassroom c: school.getClassrooms()){
            Object[] row = new  Object[4];
            row[0] = c;
            row[1] = c.getGroupnum();
            row[2] = c.getMaxgroupnum();
            row[3] = c.getStudentnum();
            
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClassRoom;
    // End of variables declaration//GEN-END:variables
}
