/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.CSYE6200.daycare.UserInterface;

import edu.neu.CSYE6200.daycare.API.AbstractClassroom;
import edu.neu.CSYE6200.daycare.API.AbstractGroup;
import edu.neu.CSYE6200.daycare.Architecture.Schedule;
import edu.neu.CSYE6200.daycare.Architecture.School;
import edu.neu.CSYE6200.daycare.Architecture.Student;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kcnuk
 */
public class ViewStudentJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private School school;
    private Student student;
    /**
     * Creates new form ViewStudentJPanel
     */
    public ViewStudentJPanel(JPanel userProcessContainer, School school, Student student) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.school = school;
        this.student = student;
        populateStatus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNextTime = new javax.swing.JTextField();
        txtNextName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBirthDay = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGroupID = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStatus = new javax.swing.JTable();
        btnMark = new javax.swing.JButton();

        setBackground(new java.awt.Color(216, 233, 239));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Student Information:");

        jLabel10.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jLabel10.setText("Inoculated Status :");

        jLabel9.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel9.setText("Next Inoculated Time :");

        txtNextTime.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtNextTime.setEnabled(false);

        txtNextName.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtNextName.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel8.setText("Next Vaccine Name :");

        jLabel7.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel7.setText("Birthday :");

        txtBirthDay.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtBirthDay.setEnabled(false);

        txtAge.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtAge.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel6.setText("Age :");

        jLabel5.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel5.setText("Last Name :");

        txtLastName.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtLastName.setEnabled(false);

        txtFirstName.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtFirstName.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel4.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel3.setText("Group ID :");

        txtGroupID.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtGroupID.setEnabled(false);

        txtID.setFont(new java.awt.Font("微软雅黑", 0, 18)); // NOI18N
        txtID.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        jLabel2.setText("ID :");

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(216, 233, 239));
        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 0, 0));
        btnUpdate.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(216, 233, 239));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(0, 0, 0));
        btnSave.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(216, 233, 239));
        btnSave.setText("Save");
        btnSave.setEnabled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tblStatus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Name", "Inoculated Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblStatus);
        if (tblStatus.getColumnModel().getColumnCount() > 0) {
            tblStatus.getColumnModel().getColumn(0).setResizable(false);
            tblStatus.getColumnModel().getColumn(1).setResizable(false);
            tblStatus.getColumnModel().getColumn(2).setResizable(false);
        }

        btnMark.setBackground(new java.awt.Color(0, 0, 0));
        btnMark.setFont(new java.awt.Font("微软雅黑", 1, 18)); // NOI18N
        btnMark.setForeground(new java.awt.Color(216, 233, 239));
        btnMark.setText("Mark this vaccine as finished");
        btnMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(94, 94, 94)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNextName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNextTime, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE))
                .addGap(100, 100, 100))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnSave, btnUpdate});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNextTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnMark)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSave)
                                .addComponent(btnUpdate))))
                    .addComponent(jScrollPane1))
                .addGap(51, 51, 51))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel10});

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        //get the previous JPanel then pop the table again
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageStudentJPanel){
                ManageStudentJPanel panel = (ManageStudentJPanel) comp;
                panel.populateTable();
            }
        }
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtAge.setEnabled(true);
        txtBirthDay.setEnabled(true);
        txtFirstName.setEnabled(true);
        txtGroupID.setEnabled(true);
        txtID.setEnabled(true);
        txtLastName.setEnabled(true);
        btnSave.setEnabled(true);
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String a = txtID.getText();
        try {
            Integer.parseInt(a);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID: " + a + " is not a valid int number");
            return;
        }
        int id = Integer.parseInt(a);
        // judge if a serialNum is unique
       if(Integer.parseInt(a) != id){           
            for(Student s: school.getStudents()){
            if(s.getStudentID() == id){
                JOptionPane.showMessageDialog(null, "ID " + id + " already exists");
                return;
            }
            
        }}
        int groupID = Integer.parseInt(txtGroupID.getText());
        Integer[] c = {5,13};
        Integer[] d = {12,25};
        Integer[] e = {24,36};
        Integer[] f = {35,48};
        Integer[] g = {47,60};
        Integer[] h = {59,100};
        Map<Integer, Integer[]> map = new HashMap<Integer, Integer[]>();
        map.put(4, c);
        map.put(5, d);
        map.put(6, e);
        map.put(8, f);
        map.put(12, g);
        map.put(15, h);
        int flag = 0;
        for(AbstractGroup group: school.getGroups()){
            if(group.getGroupID() == groupID){
                flag = 1;
                break;
            }
        }
        int x = Integer.parseInt(txtGroupID.getText());
        if( x != 0){
        if(flag == 0){
            JOptionPane.showMessageDialog(null, "GroupID " + groupID + " doesn't exist");
            return;
        }}
        int agecheck = Integer.parseInt(txtAge.getText());
        for(AbstractGroup group: school.getGroups()){
            int rule = group.getGrouprule();
            System.out.println("***************************************************");
            System.out.println(rule);
            System.out.println(rule);
            if(group.getGroupID() == groupID){
                if(map.get(rule)[0] > agecheck || map.get(rule)[1] < agecheck){
                    JOptionPane.showMessageDialog(null, "This GroupID " + groupID + " has students from other age period");
                    return;
                }
            }
        }
        
        String firstName = txtFirstName.getText();
        if(firstName.equals("")){
            JOptionPane.showMessageDialog(null, "Please set a First Name");
            return;
        }
        String lastName = txtLastName.getText();
        if(lastName.equals("")){
            JOptionPane.showMessageDialog(null, "Please set a Last Name");
            return;            
        }
        String b = txtAge.getText();
        try {
            Integer.parseInt(b);
        } catch (NumberFormatException n) {
            JOptionPane.showMessageDialog(null, "Age: " + b + " is not a valid int number");
            return;
        }
        int age = Integer.parseInt(b);
        
        String birthDay = txtBirthDay.getText();
        if(!birthdatePatternCorrect()){
            JOptionPane.showMessageDialog(null, "Birthdate should use format as MM/DD/YYYY");
            return;
        }
        String nextd = txtNextTime.getText();
        String nextn = txtNextName.getText();
        Student s = school.getStudentfactory().getstudentInstance(age, firstName, lastName, id, groupID, birthDay, nextn, nextd);
        school.updateStudent(s);
        
        txtFirstName.setEnabled(false);
        txtLastName.setEnabled(false);
        txtID.setEnabled(false);
        txtBirthDay.setEnabled(false);
        txtAge.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnSave.setEnabled(false);

        JOptionPane.showMessageDialog(null, "Student successfully updated!");        
    }//GEN-LAST:event_btnSaveActionPerformed
    private boolean birthdatePatternCorrect(){
        Pattern p = Pattern.compile("\\d{4}\\/\\d{1,2}\\/\\d{1,2}");
        Matcher m = p.matcher(txtBirthDay.getText());
        boolean b = m.matches();
        return b;
    }
    private void btnMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkActionPerformed
        // TODO add your handling code here:
        school.setStudentVaccine(student);
        txtNextName.setText(student.getNextvaccinename());
        txtNextTime.setText(student.getNextvaccinedate());
        
        DefaultTableModel dtm = (DefaultTableModel) tblStatus.getModel();
        dtm.setRowCount(0);
        for(Schedule.Immunization i: student.getSchedule().getImmunizations()){
            Object[] row = new  Object[3];
            row[0] = i;
            row[1] = i.getImmunizationdate();
            row[2] = i.getStatus();
            
            dtm.addRow(row);
        }        
        JOptionPane.showMessageDialog(null, "Student's next inoculated status successfully updated!");
    }//GEN-LAST:event_btnMarkActionPerformed

    void populateStatus(){
        txtID.setText(String.valueOf(student.getStudentID()));
        txtGroupID.setText(String.valueOf(student.getGroupID()));
        txtFirstName.setText(student.getFirstname());
        txtLastName.setText(student.getLasstname());
        txtAge.setText(String.valueOf(student.getAge()));
        txtBirthDay.setText(student.getBirthday());
        txtNextName.setText(student.getNextvaccinename());
        txtNextTime.setText(student.getNextvaccinedate());
        
        DefaultTableModel dtm = (DefaultTableModel) tblStatus.getModel();
        dtm.setRowCount(0);
        for(Schedule.Immunization i: student.getSchedule().getImmunizations()){
            Object[] row = new  Object[3];
            row[0] = i;
            row[1] = i.getImmunizationdate();
            row[2] = i.getStatus();
            
            dtm.addRow(row);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnMark;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStatus;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtBirthDay;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGroupID;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNextName;
    private javax.swing.JTextField txtNextTime;
    // End of variables declaration//GEN-END:variables
}
